export const destination =[
    {
        id :1,
        title: 'Coxs Bazar',
        country: 'Bangladesh',
        details: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
        img: 'https://media-cdn.tripadvisor.com/media/photo-c/2560x500/10/e2/f8/43/longest-sea-beach-in.jpg',
    },
    {
        id :2,
        title: 'St. Martin',
        country: 'Bangladesh',
        details: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
        img: 'https://dailyasianage.com/library/2018/04/07/1523127044_3.jpg',
    },
    {
        id :3,
        title: 'Jaflong',
        country: 'Bangladesh',
        details: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
        img: 'https://1.bp.blogspot.com/-q6eeZwXDv3k/X7kIsfj55UI/AAAAAAAAAeQ/7GVuuyGpjwg454YlyRVRlC-vvrFA9wxCwCLcBGAsYHQ/s550/Tourist%2Bdestination%2B%2BJaflong%2B%2BBangladesh.jpg',
    },
    {
        id :4,
        title: 'Kuakata',
        country: 'Bangladesh',
        details: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
        img: 'https://porzoton.com/wp-content/uploads/2020/04/Red-Crab-Island-Kuakata.jpg',
    },
    {
        id :5,
        title: 'Khagrachari',
        country: 'Bangladesh',
        details: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
        img: 'http://2.bp.blogspot.com/-vjIx1swIpic/UQLOlVo-WXI/AAAAAAAABZk/FmLmEW6cius/s1600/Khagrachari.jpg',
    },
    {
        id :6,
        title: 'Moynamoti',
        country: 'Bangladesh',
        details: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
        img: 'https://grambanglatourtravel.com/wp-content/uploads/2017/01/moinamoti.jpeg',
    },
    {
        id :7,
        title: 'National ',
        country: 'Indonesia',
        details: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
        img: 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Jatiyo_Sriti_Shoudho_%28%E0%A6%9C%E0%A6%BE%E0%A6%A4%E0%A7%80%E0%A6%AF%E0%A6%BC_%E0%A6%B8%E0%A7%8D%E0%A6%AE%E0%A7%83%E0%A6%A4%E0%A6%BF_%E0%A6%B8%E0%A7%8C%E0%A6%A7%29.jpg',
    },
]